### ISSUE TITLE
Platform should offer experiment termination

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#91]
## Description
The UI has to offer the user who started an experiment the possibility to remove the experiment from the queue or to stop it if it was already running.

* The user who created the experiment needs to be added to the internal experiment metadata of the platform controller (a challenge owner will be used as the owner of all experiments that are part of the challenge).
* The status information that is requested by the GUI backend contains this ownership information.
* The UI for the queue content has to be updated to offer a button to stop/remove an experiment if the user is the "owner" of the experiment
* The experiment results don’t have to be stored since the user stopped the experiment by himself

Note that this issue is blocked by #90

## Tasks
- [x] INFAI (@MichaelRoeder, @denkv) implements the functionality to stop/remove experiments
- [x] INFAI (@MichaelRoeder, @denkv) implements  the storing of the user who started the experiment
- [x] USU (@Ennosigaeon) adapts the UI by adding a stop (or remove) button if the current user is the experiment owner
- [x] USU (@Ennosigaeon) adds backend call to actually issue a cancel request

**Comment by MichaelRoeder** [comment]
Updated the description after our telco

**Comment by MichaelRoeder** [comment]
The storage of the experiment owner has been added to the GUI and the platform. The beans that are used for the status page (see #90) contain a `canBeCanceled` flag. If this is true, the front end should offer the canceling of the experiment to the user.

The stopping itself has not been fully added until now. However, you can already add the button. We still need a rest URL that it can call which calls the functionality in the platform controller client.

**Comment by Ennosigaeon** [comment]
Button was added in [feature/newStatusPage](https://github.com/hobbit-project/platform/tree/feature/newStatusPage), but nothing happens yet when the button is clicked.

**Comment by MichaelRoeder** [comment]
The backend is not completely ready for pressing the button. Will add this functionality ASAP.

**Comment by MichaelRoeder** [comment]
The backend is ready, now.

I couldn't determine what the button tries to call. I used a curl command which calls `/rest/experiments/terminate/1516809338789` and the experiment has been removed as it should.

Please note that the cancel button should not only be shown for experiments in the queue but also for experiments that are currently running. It would also be good to disable the button to make sure that the user does not click multiple times on it because removing an experiment (espcially stopping the running experiment) can take some time.

Please note that the only response that the gui client gets is the HTTP status. If it is `200 OK`, the removing was successful. `304 NOT MODIFIED` means that the removing did not took place (most probably because the user was not allowed to do request it but this shouldn't happen) and `500` will be returned if an error occurred.

**Comment by Ennosigaeon** [comment]
So far, the button didn't do anything. I have added the call to the backend now.

**Comment by MichaelRoeder** [comment]
Yes, the button words.

Could you please add it to the currently running experiment as well?

**Comment by Ennosigaeon** [comment]
Done.

**Comment by MichaelRoeder** [comment]
For documentation: the termination of the experiment by the user increases the probability of #39 to occur.
